---
title: "stanEx1-1"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: show 
#date: "`r Sys.Date()`"

---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,warning=F,message=F)
suppressWarnings(
  suppressMessages(
    suppressPackageStartupMessages({
      library(stats)
      library(MASS)
      library(tidyverse)
    })
  )
)
```

```{r}
options(scipen=100,digits=3)
library(cmdstanr)
options(mc.cores=parallel::detectCores())
options(cmdstanr_max_rows=1000)
library(gridExtra)
```

execute mcmc sampling
```{r}
goMCMC=function(mdl,data,smp=500,wrm=100,th=1){
  mcmc=mdl$sample(
  data=data,
  seed=1,
  chains=4,
  iter_sampling=smp,
  iter_warmup=wrm,
  thin=th,
  refresh=1000
  )
  mcmc
}
```

see mcmc result and parameters
```{r}
seeMCMC=function(mcmc,exc='',ch=T){ # exclude 'exc' parameters from seeing
  print(mcmc)
  prs=mcmc$metadata()$model_params[-1] # reject lp__
  for(pr in prs){
    if(grepl('^y',pr)) next # not show predictive value "y*" information
    if(exc!='' && grepl(paste0('^',exc),pr)) next
    drw=mcmc$draws(pr)
    if(ch){
      par(mfrow=c(1,4))
      drw[,1,] |> plot(type='l',main='chain1',ylab=pr)
      drw[,2,] |> plot(type='l',main='chain2',ylab=pr)
      drw[,3,] |> plot(type='l',main='chain3',ylab=pr)
      drw[,4,] |> plot(type='l',main='chain4',ylab=pr)
    }

    par(mfrow=c(1,2))
    drw |> hist(main=pr,xlab='')
    drw |> density() |> plot(main=pr)    
  }
}
```


# distributions

## normal dist.
```
distribution of mean, it's from central limit theorem
y~N(m,s), y(-Inf,Inf), E[y]=m, V[y]=s^2
```

### ex1.stan
```
data{
  int N;
  vector[N] y;
}
parameters{
  real m;
  real<lower=0> s;
}
model{
  y~normal(m,s);
}
```

```{r}
y=rnorm(10,2,1)
summary(y)
par(mfrow=c(1,2))
hist(y,main='y')
density(y) |> plot(main='y')

data=list(N=length(y),y=y)

mdl=cmdstan_model('./ex1.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

mcmc
mcmc$metadata()$stan_variables
mcmc$metadata()$model_params
seeMCMC(mcmc)
```


## Bernoulli dist.
```
The event with probablity p occur y=1, not occur y=0 
y~Ber(p), y{0,1}, E[y]=p, V[y]=p(1-p)
```
### ex0-0.stan
```
data{
  int N;
  array[N] int y;
}
parameters{
  real<lower=0,upper=1> p;
}
model{
  p~beta(1,1);
  y~bernoulli(p);
}
```

```{r}
data=list(N=9,y=sample(0:1,9,replace=T))

mdl=cmdstan_model('./ex0-0.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

mcmc
mcmc$metadata()$stan_variables
mcmc$metadata()$model_params
seeMCMC(mcmc)
```


## Poisson dist.
```
The event occur l times in unit range, the event occur y times. 
y~Po(l), y{0,1...Inf}, E[y]=l, V[y]=l
```

### ex2-2.stan
```
data{
  int N;
  array[N] int y;
}
parameters{
  real<lower=0> l;
}
model{
  y~poisson(l);
}
generated quantities{
  array[N] int y1;
  for(i in 1:N)
    y1[i]=poisson_rng(l);
}
```

```{r}
n=10
y=rpois(n,3)
summary(y)
par(mfrow=c(1,2))
hist(y,main='y')
density(y) |> plot(main='y')

data=list(N=n,y=y)

mdl=cmdstan_model('./ex2-2.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

seeMCMC(mcmc)

y1=mcmc$draws('y1')
par(mfrow=c(1,2))
hist(y1,main='y1')
density(y1) |> plot(main='y1') 
```


## binomial dist.
```
The event with probablity p occur y times on n trials
y~B(n,p), y{0,1...n}, E[y]=np, V[y]=np(1-p)
```
### ex2-3.stan
```
data{
  int N;
  array[N] int n;
  array[N] int y;
}
parameters{
  real<lower=0> p;
}
model{
  y~binomial(n,p);
}
```

```{r}
n=10
n0=floor(runif(n,1,10))
y=rbinom(n,n0,0.3)

data=list(N=n,n=n0,y=y)

mdl=cmdstan_model('./ex2-3.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

seeMCMC(mcmc)
```


## log normal dist.
```
logalithm of variable follows normal distribution
log y~N(m,s), y>0
```
### ex2-4.stan
```
data{
  int N;
  vector[N]<lower=0> y;
}
parameters{
  real m;
  real<lower=0> s;
}
model{
  y~lognormal(m,s);
}
```

```{r}
n=10
y=rlnorm(n,2,1)
summary(y)
par(mfrow=c(1,2))
hist(y,main='y')
density(y) |> plot(main='y')

data=list(N=n,y=y)

mdl=cmdstan_model('./ex2-4.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

mcmc
mcmc$metadata()$stan_variables
mcmc$metadata()$model_params
seeMCMC(mcmc)
```


## exponential dist.
```
The event occur l times in unit range, the event take time y to occur
y~ex(l), y>0, E[y]=1/l, V[y]=1/l^2
```
### ex2-5.stan
```
data{
  int N;
  vector[N] y;
}
parameters{
  real<lower=0> l;
}
model{
  y~exponential(l);
}
```

```{r}
n=10
y=rexp(n,1)
summary(y)
par(mfrow=c(1,2))
hist(y,main='y')
density(y) |> plot(main='y')

data=list(N=n,y=y)

mdl=cmdstan_model('./ex2-5.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

mcmc
mcmc$metadata()$stan_variables
mcmc$metadata()$model_params
seeMCMC(mcmc)
```


## gamma dist.
```
The event occur l times in unit range, the event take time y to occur a times
y~Ga(a,l), y>0, E[y]=a/l, V[y]=a/l^2
```
### ex2-6.stan
```
data{
  int N;
  vector[N] y;
}
parameters{
  real<lower=0> a;
  real<lower=0> l;
}
model{
  y~gamma(a,l);
}
```

```{r}
n=10
y=rgamma(n,2,1)
summary(y)
par(mfrow=c(1,2))
hist(y,main='y')
density(y) |> plot(main='y')

data=list(N=n,y=y)

mdl=cmdstan_model('./ex2-6.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

mcmc
mcmc$metadata()$stan_variables
mcmc$metadata()$model_params
seeMCMC(mcmc)
```


## beta dist.
```
use as prior of binomial dist parameter p
p~Be(a,b), p[0,1], E[p]=a/(a+b), V[p]=ab/(a+b)^2/(a+b+1)
```
### ex2-7.stan
```
data{
  int N;
  vector[N] p;
}
parameters{
  real<lower=0> a;
  real<lower=0> b;
}
model{
  p~beta(a,b);
}
```

```{r}
n=20
p=rbeta(n,1,2)
summary(p)
par(mfrow=c(1,2))
hist(p,main='p')
density(p) |> plot(main='p')

data=list(N=n,p=p)

mdl=cmdstan_model('./ex2-7.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

mcmc
mcmc$metadata()$stan_variables
mcmc$metadata()$model_params
seeMCMC(mcmc)
```


## dirichlet dist.
```
use as prior of categorical dist parameter p
p~dir(p0), p[0,1]
```
### ex2-8.stan
```
data {
  int N;
  int K;
  matrix[N, K] p;
}
parameters {
  simplex[K] p0;
}
model {
  for(i in 1:N){
     p[i]~dirichlet(p0);
  }
}
```

```{r}
library(gtools)
n=20
p=rdirichlet(n,c(0.5,0.3,0.2))
summary(p)
boxplot(p)

data=list(N=n,K=ncol(p),p=p)

mdl=cmdstan_model('./ex2-8.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)

mcmc
mcmc$metadata()$stan_variables
mcmc$metadata()$model_params
seeMCMC(mcmc)
```