---
title: "Toyota's bayesian analysis text2"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: show 
#date: "`r Sys.Date()`"

---

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,warning=F,message=F,comment='')

suppressWarnings(
  suppressMessages(
    suppressPackageStartupMessages({
      library(stats)
      library(MASS)
      library(tidyverse)
      library(magrittr)
      
      library(cmdstanr)
      library(palmerpenguins)　#サンプルデータ用
    })
  )
)
options(scipen=100,digits=3)

options(mc.cores=parallel::detectCores())
options(cmdstanr_max_rows=50)

mode=function(x,a=0) {
  as.numeric(names(which.max(table(round(x,a)))))
}

qtile=function(x) {
  quantile(x,probs=c(0.0,0.025,0.05,0.25,0.5,0.75,0.95,0.975,1),na.rm=T)
}
```

execute mcmc sampling
```{r}
goMCMC=function(mdl,data,smp=500,wrm=100,th=1){
  mcmc=mdl$sample(
  data=data,
  seed=1,
  chains=4,
  iter_sampling=smp,
  iter_warmup=wrm,
  thin=th,
  refresh=1000
  )
  mcmc
}
```

see mcmc result and parameters
```{r}
seeMCMC=function(mcmc,exc='',ch=T){ # not see parameters str1..., str2,... using regex as exc='[str1,str2,...]' 
  print(mcmc)
  prs=mcmc$metadata()$model_params[-1] # reject lp__
  for(pr in prs){
    if(grepl('^y',pr)) next # not show predictive value "y*" information
    if(exc!='' && grepl(paste0('^',exc),pr)) next
    drw=mcmc$draws(pr)
    if(ch){
      par(mfrow=c(1,4))
      drw[,1,] |> plot(type='l',main='chain1',ylab=pr)
      drw[,2,] |> plot(type='l',main='chain2',ylab=pr)
      drw[,3,] |> plot(type='l',main='chain3',ylab=pr)
      drw[,4,] |> plot(type='l',main='chain4',ylab=pr)
    }

    par(mfrow=c(1,2))
    drw |> hist(main=pr,xlab='')
    drw |> density() |> plot(main=pr)    
  }
}
```



## estimation in normal distribution

stan01.stan
```
data {
  int<lower=0> N; //number of observation
  vector[N] y; //observations
}
parameters {
  real m;//mean
  real<lower=0> s; //standard deviation
}
model {
  y~normal(m,s); //data genaration
}
generated quantities {
  real y1; //data prediction
  y1 = normal_rng(m, s);
  real ll; //log liklihood
  ll = normal_lpdf(y|m,s);
}
```

```{r}
###6.1.1 正規分布の平均に関する推測
y=c(3060, 2840, 1780, 3280, 3550, 2450, 2200,
    3070, 2100, 4100, 3630, 3060, 3280, 1870,
    2980, 3120, 2150, 3830, 4300, 1880)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./stan01.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data,smp=1000)
seeMCMC(mcmc,exc='ll',ch=F)

m=mcmc$draws('m') |> as.vector()
mode(m)
qtile(m)

sum(m>2500)/length(m)
sum(m>3000)/length(m)

s=mcmc$draws('s') |> as.vector()
mode(s)
qtile(s)
mode((m-2500)/s,2)
qtile((m-2500)/s)

sum((m-2500)/s>0.8)/length(m)
```


```{r}
###6.1.2 正規分布の分散に関する推測
y=c(
145.55, 145.41, 144.26, 145.05, 145.84, 145.06, 145.19, 145.30, 144.47,
144.84, 145.18, 145.00, 144.95, 144.88, 145.25, 145.38, 145.28, 144.66,
145.26, 144.47, 145.24, 144.29, 145.21, 144.77, 145.51, 144.33, 144.47,
144.90, 144.76, 145.46, 145.04, 144.98, 145.41, 145.45, 144.83, 144.71,
144.65, 144.21, 145.10, 145.10)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./stan01.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='ll',ch=F)

m=mcmc$draws('m') |> as.vector()
mode(m)
qtile(m)

s=mcmc$draws('s') |> as.vector()
mode(s^2,2)
qtile(s^2)

sum(s^2>0.1)/length(s)
sum(s^2>0.15)/length(s)
```


```{r}
###6.1.3 正規分布の分位に関する推測
y=c(775, 779, 799, 794, 770, 790, 775,  
778, 808, 802, 776, 775, 799, 787,
825, 785, 775, 762, 782, 788)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./stan01.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='ll',ch=F)

m=mcmc$draws('m') |> as.vector()
s=mcmc$draws('s') |> as.vector()

z=qnorm(0.75,0,1) 
mode(m+z*s)
qtile(m+z*s)

n=length(m)
sum(rnorm(n,805,10)>m+z*s)/n
```


```{r}
###6.2.1 独立な2群の平均値差に関する推測
y=c(30.86,29.75,31.55,32.29,29.90,31.71,31.35,29.03,30.37,31.55,
	  29.26,32.29,29.90,30.18,30.72,32.28,30.72,29.90,31.55,31.55)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./stan01.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='ll',ch=F)

m1=mcmc$draws('m') |> as.vector()
mode(m1)
qtile(m1)


y=c(31.36,33.34,33.16,31.36,36.19,29.80,31.11,35.23,31.36,31.27,
	  31.63,31.63,32.00,31.11,31.63,31.36,31.81,31.63,29.21,33.37)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./stan01.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='ll',ch=F)

m2=mcmc$draws('m') |> as.vector()
mode(m2)
qtile(m2)

sum(m2>m1)/length(m1)
sum(m2-m1>1)/length(m1)
```


```{r}
###6.2.2 対応のある2群の平均値差に関する推測
y1=c(6,11,10,13,17,10,10,7,9,1,14,7,7,11,12,12,14,12,7,13)
y2=c(7,11,14,13,16,12,8,15,12,3,17,11,9,11,14,12,11,15,11,17)
d=y2-y1
data=list(N=length(d),y=d)

mdl=cmdstan_model('./stan01.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='ll',ch=F)

m=mcmc$draws('m') |> as.vector()
mode(m,2)
qtile(m)

sum(m>0)/length(m)
sum(m>2)/length(m)
```

stan02.stan
```
data{
  int N;
  int K;
  array[N] vector[K] y;
}
parameters{
  vector[K] m;
  cov_matrix[K] cv;
}
model{
  y~multi_normal(m,cv);
}
generated quantities{
  vector[K] y1;
  y1=multi_normal_rng(m,cv);
  real ll;
  ll=multi_normal_lpdf(y|m,cv);
}
``` 

```{r}
y=cbind(y1,y2)
data=list(N=nrow(y),K=ncol(y),y=y)

mdl=cmdstan_model('./stan02.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data,smp=1000)
seeMCMC(mcmc,exc='ll',ch=F)

m1=mcmc$draws('m[1]') |> as.vector()
m2=mcmc$draws('m[2]') |> as.vector()
d=m2-m1

mode(d,2)
qtile(d)
sum(d>0)/length(d)
sum(d>2)/length(d)

s1=mcmc$draws('cv[1,1]') |> as.vector() |> sqrt()
s2=mcmc$draws('cv[2,2]') |> as.vector() |> sqrt()
cv=mcmc$draws('cv[1,2]') |> as.vector()
r=cv/s1/s2

mode(r,2)
qtile(r)
sum(r>0)/length(r)
sum(r>0.5)/length(r)
```



## estimation in various distributions

ex1-4.stan
```
data{
  int N;
  array[N] int y;
}
parameters{
  real<lower=0> l;
}
model{
  y~poisson(l);
}
generated quantities{
  real s;
  s=l^.5;
  int y1;
  y1=poisson_rng(l);
}
```

```{r}
###7.1.1 流れ星問題1
y=c( 1 ,0 ,0 ,3 ,0 ,0, 0, 0 ,0 ,1)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./ex1-4.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

l=mcmc$draws('l') |> as.vector()
mode(l,2)
qtile(l)

s=mcmc$draws('s') |> as.vector()
mode(s,2)
qtile(s)

y1=mcmc$draws('y1') |> as.vector()
table(y1)
sum(y1==2)/length(y1)
```


```{r}
###7.1.2 ウミガメ問題
y1=c(0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 
1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,0 ,1)
y2=c(0, 3, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 
3, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2)

data=list(N=length(y1),y=y1)

mdl=cmdstan_model('./ex1-4.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

l1=mcmc$draws('l') |> as.vector()

data=list(N=length(y2),y=y2)

mdl=cmdstan_model('./ex1-4.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

l2=mcmc$draws('l') |> as.vector()

d=l2-l1
mode(d,2)
qtile(d)
sum(d>0)/length(d)
```


ex1-5.stan
```
data{
  int N;
  vector[N] y;
}
parameters{
  real<lower=0> l;
}
model{
  y~exponential(l);
}
generated quantities{
  real m;
  m=1/l;
  real s;
  s=1/l;
  real y1;
  y1=exponential_rng(l);
}
```

```{r}
###7.2 レストラン問題
y=c(5,1,18,5,1,8,8,2,14,12)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./ex1-5.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

l=mcmc$draws('l') |> as.vector()
mode(1/l,2)
qtile(1/l)

y1=mcmc$draws('y1') |> as.vector()
mode(y1,2)
qtile(s)

sum(y1<=5)/length(y1)
```


```{r}
###7.3 流れ星問題2
y=c( 1 ,0 ,0 ,3 ,0 ,0, 0, 0 ,0 ,1)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./ex1-4.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

l=mcmc$draws('l') |> as.vector()
y1=rgamma(length(l),3,l)*5
mode(y1,2)
qtile(y1)
```


ex1-2.stan (geometric dist.)
```
data{
  int N;
  array[N] int y;
}
parameters{
  real<lower=0,upper=1> p;
}
model{
  for (n in 1:N) {
    target+=log(p)+y[n]*log(1-p);
  }
}
generated quantities{
  real m;
  m=1/p;
  real s;
  s=((1-p)/p^2)^.5;
}
```

```{r}
###7.4 当たり付き棒アイス問題
y=c(19, 34, 11, 26, 22, 30)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./ex1-2.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

p=mcmc$draws('p') |> as.vector()
mode(p,2)
qtile(p)
sum(p>1/36)/length(p)

mode(1/p,2)
qtile(1/p)

y1=rgeom(length(p),p)
table(y1)
sum(y1==3)/length(y1)
```


ex1-1.stan
```
data{
  int N;
  array[N] int y;
}
parameters{
  real<lower=0,upper=1> p;
}
model{
  p~beta(1,1);
  y~bernoulli(p);
}
generated quantities{
  real s;
  s=(p*(1-p))^.5;
}
```

```{r}
###7.5 エントリーシート問題
y=c(0,0,0,1,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./ex1-1.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

p=mcmc$draws('p') |> as.vector()

y1=rnbinom(length(p),2,p)
sum(y1<=3)/length(y1)
qtile(y1)
```


ex1-7.stan
```
data{
  int N;
  vector[N] y;
}
parameters{
  real m0;
  real<lower=0> s0;
}
model{
  y~lognormal(m0,s0);
}
generated quantities{
  real m;
  m=exp(m0+s0^2);
  real s;
  s=(exp(2*m0+s0^2)*(exp(s0^2)-1))^.5;
  real y1;
  y1=lognormal_rng(m0,s0);
}
```

```{r}
###7.6 婚活問題
y=c(1320, 230, 420, 320, 530, 100, 740, 750, 1110, 230,
    800, 540, 230, 280, 1110, 430, 730, 230, 120, 200,
    370, 170, 530, 140, 660, 440, 650, 110, 690)
data=list(N=length(y),y=y)

mdl=cmdstan_model('./ex1-7.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

m0=mcmc$draws('m0') |> as.vector()
s0=mcmc$draws('s0') |> as.vector()

z=qnorm(0.7,0,1)
y0=exp(m0+z*s0)
mode(y0)
qtile(y0)

sum(y0<450)/length(y0)
```



## proportion, correlation

ex16-1.stan
```
data {
  int n0;
  int n01;
  int n1;
  int n11;
}
parameters {
  real<lower=0,upper=1> p01;
  real<lower=0,upper=1> p11;
}
model {
  n01~binomial(n0,p01);
  n11~binomial(n1,p11);
}
generated quantities {
  real RR;
  RR=p11/p01;
  real OR;
  OR=(p11/(1-p11))/(p01/(1-p01));
}
```

```{r}
n0=200
n01=97
n1=200
n11=128
data=list(n0=n0,n01=n01,n1=n1,n11=n11)

mdl=cmdstan_model('./ex16-1.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,ch=F)

p01=mcmc$draws('p01') |> as.vector()
p11=mcmc$draws('p11') |> as.vector()
d=p11-p01

qtile(d)
sum(d>0)/length(d)
```


stan02.stan
```
data{
  int N;
  int K;
  array[N] vector[K] y;
}
parameters{
  vector[K] m;
  cov_matrix[K] cv;
}
model{
  y~multi_normal(m,cv);
}
generated quantities{
  vector[K] y1;
  y1=multi_normal_rng(m,cv);
  real ll;
  ll=multi_normal_lpdf(y|m,cv);
}
``` 

```{r}
###8.2 2群の相関係数の差に関する推測
ya=matrix(c(
11,6,10,8,10,14,5,9,15,10,8,8,14,10,11,8,12,11,12,9,6,10,12,11,8,10,8,9,7,5,8,10,14,15,5,11,5,7,5,11,10,9,14,11,10,11,13,10,15,15,15,5,8,16,6,11,9,10,9,16,13,9,10,17,8,7,14,9,9,12,7,17,15,13,9,10,11,5,4,9,11,11,3,12,14,12,9,8,9,12,9,13,15,11,14,11,7,15,13,11,10,14,2,11,14,12,12,9,11,10,13,12,8,6,10,11,10,11,13,9,9,12,13,9,12,11,11,13,13,10,17,8,11,8,9,13,6,17,9,14,11,10,7,13,13,8,9,9,7,9,8,11,14,9,8,10,8,8,2,8,5,9,10,8,17,7,11,8,10,7,8,12,9,11,6,11,5,12,9,7,14,9,10,7,5,12,6,11,10,9,6,7,11,4,12,9,14,9,4,12,
12,10,12,10,10,14,9,11,14,9,9,9,13,13,13,10,13,10,13,11,10,11,10,12,9,8,10,11,12,8,11,6,9,12,9,15,10,11,10,15,12,11,12,12,13,10,13,9,14,13,14,6,11,14,8,10,9,8,10,12,12,8,13,15,9,9,13,13,7,14,5,14,13,12,13,12,12,10,8,12,12,13,9,11,10,13,13,11,10,10,8,13,13,9,12,14,7,14,11,10,13,15,9,10,14,11,11,11,12,10,12,15,13,12,13,11,10,11,14,11,9,14,15,9,9,10,13,13,15,14,14,9,11,11,11,13,10,13,9,13,11,13,10,12,13,8,9,12,11,10,12,13,12,11,11,12,9,11,9,9,11,9,10,11,13,10,12,8,9,9,12,10,12,9,10,12,8,11,9,9,13,9,10,10,9,11,8,13,9,12,10,9,9,6,12,10,12,8,10,12
),nrow=200)

yb=matrix(c(
16,12,13,15,10,16,10,12,12,16,15,15,14,13,9,12,10,10,16,15,12,15,13,15,12,15,11,14,17,13,9,14,13,14,8,10,8,10,12,12,17,11,10,12,7,11,8,13,10,7,7,11,13,11,12,9,16,10,8,10,10,10,12,15,9,9,13,10,15,12,15,14,12,13,11,13,13,12,15,10,13,8,13,9,10,16,11,13,12,15,16,12,12,11,11,13,16,12,10,14,10,14,14,16,10,12,15,9,16,13,10,12,7,11,12,12,9,6,9,10,16,10,10,16,11,9,13,16,17,14,12,8,11,9,11,13,12,11,10,12,13,14,12,16,16,9,12,13,11,15,11,10,12,8,11,9,9,14,14,12,14,13,9,12,10,14,15,14,12,8,6,11,11,9,12,14,10,9,12,13,7,13,8,14,12,12,12,13,12,10,10,13,17,11,13,13,8,13,17,13,
14,12,15,13,11,17,11,13,13,14,14,12,14,15,11,13,14,12,16,17,13,16,17,16,15,15,13,11,17,15,14,15,14,14,8,12,11,12,14,12,16,11,9,13,10,13,10,14,12,11,8,14,14,14,12,11,16,12,9,13,10,12,15,16,10,11,13,11,13,10,15,11,10,15,13,13,13,15,16,9,17,9,12,12,12,15,17,12,15,14,14,15,13,13,11,15,14,12,13,14,13,12,13,16,11,12,15,13,14,14,11,11,12,13,16,12,10,8,10,13,15,9,12,15,13,12,12,13,16,14,12,11,10,10,14,14,13,12,12,14,13,14,13,14,14,12,15,12,13,15,12,12,12,11,14,12,11,16,15,12,16,13,11,14,11,12,14,15,14,10,8,13,15,11,14,13,13,12,12,16,11,14,10,13,15,12,14,14,15,14,12,13,17,13,13,14,10,13,19,13
),nrow=200)

data=list(N=nrow(ya),K=ncol(ya),y=ya)

mdl=cmdstan_model('./stan02.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='[ll,m,cv]',ch=F)

s1=mcmc$draws('cv[1,1]') |> as.vector() |> sqrt()
s2=mcmc$draws('cv[2,2]') |> as.vector() |> sqrt()
cv=mcmc$draws('cv[1,2]') |> as.vector()
ra=cv/s1/s2

mode(ra,2)
qtile(ra)

data=list(N=nrow(yb),K=ncol(yb),y=yb)

mdl=cmdstan_model('./stan02.stan')

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='[ll,m,cv]',ch=F)

s1=mcmc$draws('cv[1,1]') |> as.vector() |> sqrt()
s2=mcmc$draws('cv[2,2]') |> as.vector() |> sqrt()
cv=mcmc$draws('cv[1,2]') |> as.vector()
rb=cv/s1/s2

mode(rb,2)
qtile(rb)

d=rb-ra
mode(d,2)
sum(d>0)/length(d)
```


ex11-0.stan
```
data{
  int N0;
  array[N0] vector[2] xy;
  int N1;
  vector[N1] x1;
}
parameters{
  vector[2] m;
  cov_matrix[2] s;
}
model{
  target+=multi_normal_lpdf(xy | m, s);
  x1~normal(m[1],s[1,1]^.5);
}
generated quantities{
  vector[2] xy1;
  xy1=multi_normal_rng(m,s);
  real cr;
  cr=s[1,2]/(s[1,1]*s[2,2])^.5;
}
```

```{r}
###8.4 切断データの相関係数の推定
x0=c(
102.03,100.021,106.896,101.377,106.666,106.856,106.283,102.021,121.985,100.569,121.94,112.031,108.223,112.76,113.05,100.746,101.025,106.245,103.151,100.201,112.689,111.177,103.05,103.505,106.19,107.896,102.991,114.977,118.362,106.395,109.559,107.448,106.31,104.488,115.524,109.301,103.69,103.085,110.463,120.259,105.924,101.278,104.557,107.144,103.712,103.082,103.68,100.827,108.754,113.234,103.457,116.65,109.066,109.126,105.76,100.83,105.764,101.726,119.707,114.521,121.871,120.465,100.403,105.934,105.717,102.085,113.606,102.805,107.159,110.142,111.876,109.786,107.352,104.63,102.26,120.779,105.601,102.545,105.16,120.547,128.796,113.891,108.876,139.733,108.256,126.098,103.926,102.735,112.503,101.49,133.44,116.673,100.689,116.804,101.775,106.207,107.46,103.507,115.666,111.644,103.767,100.883,105.852,112.799,100.046,122.549,107.527,104.543,110.155,103.333,108.286,102.216,101.855,102.281,102.844,115.864,112.526,130.022,100.223,106.315,103.711,103.586)

y0=c(
98.045,96.033,123.283,107.59,107.208,129.971,115.929,114.757,136.362,104.839,121.687,120.007,99.866,109.329,128.378,124.048,103.538,109.645,97.872,103.528,109.151,112.933,115.748,104.311,94.237,103.437,104.498,105.271,126.66,105.026,100.875,98.136,92.122,100.075,123.251,104.811,105.385,115.617,116.049,108.832,110.559,108.036,99.25,113.701,123.181,119.613,96.444,103.741,119.377,101.273,103.408,121.15,106.866,91.142,98.812,105.474,101.994,117.242,108.987,107.522,108.948,139.479,117.521,87.594,98.026,110.909,99.027,117.408,114.01,114.542,112.761,141.939,111.53,101.998,95.751,133.996,99.954,115.285,125.597,140.997,151.571,96.12,126.341,141.881,112.872,129.171,91.797,115.774,125.598,101.204,129.889,122.54,94.311,121.264,106.921,103.722,118.718,95.837,102.577,116.035,108.877,104.545,116.468,118.603,83.394,125.9,108.083,109.303,116.327,101.569,103.356,110.803,89.975,99.76,90.28,110.885,109.124,128.54,104.989,101.649,106.036,103.044)

x1=c(92.778,90.763,74.895,76.563,75.780,92.271,97.853,59.926,68.232,87.168,
60.679,74.210,89.044,92.398,87.633,76.967,76.990,94.375,79.749,86.290,
71.310,86.656,76.314,78.337,87.572,86.835,88.984,83.555,78.106,99.594,
99.716,80.663,95.969,99.625,97.966,93.259,69.623,76.253,93.938,69.489,
89.165,99.260,94.149,93.719,98.537,87.032,53.840,75.218,80.128,82.080,
82.379,88.441,64.408,94.629,88.054,95.910,85.205,68.454,78.671,99.460,
90.085,89.524,81.598,82.478,89.078,94.710,64.879,82.871,72.201,80.694,
73.904,85.503,71.085,96.748,92.722,77.958,97.553,87.382,78.393,86.604,
69.770,70.804,88.473,83.499,88.485,78.401,98.552,83.416,65.192,80.918,
99.396,87.640,77.840,85.153,75.668,79.775,78.551,90.625,78.581,70.315,
83.341,87.583,97.940,92.793,77.938,80.397,91.404,87.997,92.891,57.937,
84.740,94.407,65.642,59.948,83.795,80.806,93.000,80.847,83.315,97.992,
85.633,73.850,79.639,67.908,90.344,73.529,85.575,78.586,87.641,76.970,
83.496,96.088,76.913,97.156,98.623,76.815,70.484,64.720,79.551,65.658,
92.738,86.001,90.032,74.692,80.337,62.195,66.800,79.262,97.051,91.678,
67.839,71.227,79.439,99.128,75.480,90.311,98.196,76.827,90.413,87.625,
78.881,83.516,88.184,99.990,76.814,94.771,70.086,78.324,64.240,81.577,
99.636,71.225,93.568,83.717,78.368,88.001,94.336,47.721,90.196,83.774,
80.972,92.054,89.718,70.808,97.040,93.830,88.374,86.363,84.294,99.765,
71.703,88.205,73.283,94.325,90.334,92.049,80.537,75.480,56.570,84.485,
83.926,71.004,97.441,75.607,81.497,88.923,94.228,64.545,68.394,98.694,
75.382,94.511,67.752,80.254,74.560,85.621,81.654,87.404,86.412,85.358,
95.977,83.134,93.554,95.142,72.880,86.519,84.832,93.384,76.187,98.590,
84.146,89.214,92.090,96.433,95.684,99.829,96.165,88.995,82.328,97.483,
97.997,73.627,84.399,97.789,95.837,70.280,87.186,94.825,89.206,82.598,
85.393,98.309,87.955,73.365,91.212,91.387,52.977,87.733,76.999,87.194,
93.908,74.644,87.032,86.300,67.797,69.811,90.160,82.706,82.227,85.116,
72.651,78.353,96.654,98.919,85.477,83.603,81.339,59.270,79.932,63.814,
76.123,75.678,80.842,75.515,93.870,80.323,89.415,74.626,98.940,89.783,
99.285,71.001,82.427,82.465,82.367,54.786,82.480,74.680,70.487,95.574,
65.716,66.636,88.876,81.173,89.905,97.424,95.053,79.831,80.962,84.730,
81.272,86.522,65.581,97.475,56.827,82.475,91.686,81.038,64.362,93.628,
78.931,95.370,94.726,81.443,88.405,75.052,93.349,96.183,84.029,99.298,
81.080,94.341,98.725,87.596,85.528,72.957,95.857,84.570,97.017,92.284,
90.596,76.659,90.674,90.360,98.316,75.047,89.856,91.460,86.320,95.374,
97.514,72.316,92.819,93.323,69.564,92.292,76.374,61.263,80.604,93.053,
76.563,62.843,92.798,93.469,86.351,77.873,72.567,88.382,70.631,79.970,
78.422,84.151,92.806,82.597,81.430,89.800,88.327,86.549)

xy=cbind(x0,y0)
data=list(N0=nrow(xy),xy=xy,N1=length(x1),x1=x1)

mdl=cmdstan_model('./ex11-0.stan') 

mle=mdl$optimize(data=data)
mle

mcmc=goMCMC(mdl,data)
seeMCMC(mcmc,exc='[s,xy1]',ch=F)

cr=mcmc$draws('cr') |> as.vector()
mode(cr,2)
qtile(cr)
```

